export const COUNTRIES = [
  "Nepal",
  "Poland",
  "Romania",
  "Croatia",
  "Malta",
  "Cyprus",
  "Portugal",
  "United Kingdom",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Albania",
  "Andorra",
  "Armenia",
  "Austria",
  "Azerbaijan",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Italy",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "Vatican City",
  "Sri Lanka",
  "India",
  "Pakistan",
  "Bangladesh",
  "Philippines",
];

export const countryToCode: Record<string, string> = {
  Albania: "al",
  Andorra: "ad",
  Armenia: "am",
  Austria: "at",
  Azerbaijan: "az",
  Belarus: "by",
  Belgium: "be",
  "Bosnia and Herzegovina": "ba",
  Bulgaria: "bg",
  Croatia: "hr",
  Cyprus: "cy",
  "Czech Republic": "cz",
  Denmark: "dk",
  Estonia: "ee",
  Finland: "fi",
  France: "fr",
  Georgia: "ge",
  Germany: "de",
  Greece: "gr",
  Hungary: "hu",
  Iceland: "is",
  Ireland: "ie",
  Italy: "it",
  Kosovo: "xk",
  Latvia: "lv",
  Liechtenstein: "li",
  Lithuania: "lt",
  Luxembourg: "lu",
  Malta: "mt",
  Moldova: "md",
  Monaco: "mc",
  Montenegro: "me",
  Netherlands: "nl",
  "North Macedonia": "mk",
  Norway: "no",
  Poland: "pl",
  Portugal: "pt",
  Romania: "ro",
  "San Marino": "sm",
  Serbia: "rs",
  Slovakia: "sk",
  Slovenia: "si",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Turkey: "tr",
  Ukraine: "ua",
  "United Kingdom": "gb",
  "Vatican City": "va",
  "United Arab Emirates": "ae",
  "Saudi Arabia": "sa",
  Qatar: "qa",
  Kuwait: "kw",
  Oman: "om",
  Bahrain: "bh",
  Nepal: "np",
  "Sri Lanka": "lk",
  India: "in",
  Pakistan: "pk",
  Bangladesh: "bd",
  Philippines: "ph",
};

export const CATEGORY_TO_POSITIONS: Record<string, string[]> = {
  "Civil & Architectural": [
    "Construction Worker",
    "Mason",
    "Carpenter",
    "Steel Fixer",
    "Scaffolder",
    "Painter",
    "Civil Engineer",
    "Foreman",
    "Tile Setter",
  ],
  "Electrical & Mechanical": [
    "Electrician",
    "HVAC Technician",
    "Plumber",
    "Welder",
    "Mechanical Technician",
    "Auto Mechanic",
    "Pipe Fitter",
  ],
  Security: [
    "Security Guard",
    "Bouncer",
    "CCTV Operator",
    "Security Supervisor",
    "Patrol Officer",
  ],
  "Heavy Equipment & Drivers": [
    "Driver (Light)",
    "Driver (Heavy)",
    "Delivery Rider",
    "Forklift Operator",
    "Crane Operator",
    "Excavator Operator",
    "Truck Driver",
  ],
  "Warehouse Sector": [
    "Warehouse Worker",
    "Picker",
    "Packer",
    "Storekeeper",
    "Inventory Clerk",
    "Logistics Coordinator",
    "Loading/Unloading Worker",
  ],
  Administration: [
    "HR Assistant",
    "Administrative Assistant",
    "Receptionist",
    "Data Entry Operator",
    "Accountant",
    "Customer Service Representative",
    "Office Boy/Girl",
  ],
  "Hotel & Hospitality": [
    "Waiter/Waitress",
    "Cook/Chef",
    "Kitchen Helper",
    "Bartender",
    "Barista",
    "Bellboy",
    "Room Attendant",
    "Restaurant Staff",
  ],
  "Agriculture & Plantation": [
    "Farm Worker",
    "Tractor Driver",
    "Greenhouse Worker",
    "Harvest Worker",
    "Agriculture Technician",
    "Fruit Picker",
  ],
  "Denting & Painting": [
    "Auto Denting Technician",
    "Auto Painter",
    "Industrial Painter",
    "Spray Painter",
  ],
  "Supermarkets / Hypermarkets": [
    "Cashier",
    "Sales Associate",
    "Merchandiser",
    "Supermarket Helper",
    "Butcher",
    "Baker",
    "Trolley Boy",
  ],
  "Cleaning & Housekeeping": [
    "Cleaner",
    "Housekeeper",
    "Laundry Worker",
    "Janitor",
    "Office Cleaner",
    "Street Cleaner",
  ],
  "Medical / Paramedical": [
    "Nurse",
    "Caregiver",
    "Medical Assistant",
    "Pharmacist Assistant",
    "Lab Technician",
    "Physiotherapist",
  ],
  "Manufacturing & Production": [
    "Production Worker",
    "Machine Operator",
    "Quality Control Inspector",
    "Assembly Line Worker",
    "Factory Worker",
  ],
  "IT & Software": [
    "IT Support Technician",
    "Software Developer",
    "Network Engineer",
    "Systems Administrator",
    "UI/UX Designer",
  ],
};

export const JOB_CATEGORIES = Object.keys(CATEGORY_TO_POSITIONS);
// Deduplicate just in case
export const JOB_POSITIONS = Array.from(
  new Set(Object.values(CATEGORY_TO_POSITIONS).flat()),
);

export const CURRENCIES = ["EUR", "NPR", "INR", "AED", "USD"] as const;

export const CURRENCY_SYMBOLS: Record<string, string> = {
  EUR: "€",
  NPR: "Rs",
  INR: "₹",
  AED: "د.إ",
  USD: "$",
};
